//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int ИД { get; set; }
        public int Ученик { get; set; }
        public int Препод_Предмет { get; set; }
        public int Оценка { get; set; }
        public int Вид_Оценки { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Классы_преподователей Классы_преподователей { get; set; }
        public virtual Ученик Ученик1 { get; set; }
    }
}
