//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученик
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ученик()
        {
            this.Оценки = new HashSet<Оценки>();
        }
    
        public int ИД { get; set; }
        public string Логин { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Класс { get; set; }
    
        public virtual Класс Класс1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
